# Generated by Django 4.2.9 on 2024-03-08 08:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_favorite_unique_favorite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientsrecipe',
            options={'verbose_name': 'Связь ингредиента и рецепта', 'verbose_name_plural': 'Связь ингредиентов и рецептов'},
        ),
        migrations.AlterField(
            model_name='ingredientsrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=recipes.validators.CustomTimeValidate(validators=[django.core.validators.MinValueValidator(1, message='Даже мама не может так быстро готовить!'), django.core.validators.MaxValueValidator(1440, message='Так может готовить только папа!')], verbose_name='Время приготовления в минутах'),
        ),
    ]
