# Generated by Django 3.2.3 on 2024-03-27 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_username_alter_subscrime_author_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscrime',
            name='unique_subscribers',
        ),
        migrations.AlterField(
            model_name='subscrime',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddConstraint(
            model_name='subscrime',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscriber'),
        ),
    ]
